services:
  patient-service-db:
    image: postgres
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin_user
    networks:
      - internal
    volumes:
      - patient-service-db:/var/lib/postgresql/data

  auth-service-db:
    image: postgres
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin_user
    networks:
      - internal
    volumes:
      - auth-service-db:/var/lib/postgresql/data

  patient-service:
    build: ./patient-service/
    image: patient-service:latest
    ports:
      - "4000:4000"
    networks:
      - internal
    environment:
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_SQL_INIT_MODE=always

  auth-service:
    build: ./auth-service/
    image: auth-service:latest
    ports:
      - "4005:4005"
    networks:
      - internal
    environment:
      - JWT_SECRET=Y2FiaW5mYXJtbGF0ZXJicmVlemV1bml2ZXJzZWJ1c3liaWdnZXJzdHJhaWdodHRodXM=
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always

  billing-service:
    build: ./billing-service/
    image: billing-service:latest
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  analytics-service:
    build: ./analytics-service/
    image: analytics-service:latest
    ports:
      - "4002:4002"
    networks:
      - internal

  api-gateway:
    build: ./api-gateway/
    image: api-gateway:latest
    ports:
      - "4004:4004"
    networks:
      - internal
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0;KAFKA_CFG_PROCESS_ROLES=controller,broker
networks:
  internal:
volumes:
  patient-service-db:
  auth-service-db:


